=begin
#Phone.com API

#This is a Phone.com api Swagger definition

OpenAPI spec version: 1.0.0
Contact: apisupport@phone.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::DeleteMedia
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DeleteMedia' do
  before do
    # run before each test
    @instance = SwaggerClient::DeleteMedia.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DeleteMedia' do
    it 'should create an instact of DeleteMedia' do
      expect(@instance).to be_instance_of(SwaggerClient::DeleteMedia)
    end
  end
  describe 'test attribute "success"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

